import type { Metadata } from "next";
import { Inter } from "next/font/google";
import LiffProvider from "./LiffProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <LiffProvider>
        <body className={inter.className}>{children}</body>
      </LiffProvider>
    </html>
  );
}
